apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller-demo
spec:
  replicas: 3
  selector:
    app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: interviewdot/demo-k8s:0.5.0
        ports:
        - containerPort: 80
